[build]
  publish = "dist"
  command = "npm run build"

# --- Headers ---
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/sitemap-v2.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "no-cache, no-store, must-revalidate"

# --- Redirects ---
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-v2.xml"
  to = "/sitemap-v2.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Keep SPA fallback at the very end
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
