[build]
  publish = "dist"
  command = "npm run build"

# --- Headers ---
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/sitemap-v2.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "no-cache, no-store, must-revalidate"

# --- Redirects ---
# Ensure sitemap and robots.txt bypass SPA fallback completely
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/sitemap-v2.xml"
  to = "/sitemap-v2.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# SPA fallback must remain last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
